export const RESPONSES = Object.freeze([
  "Yes.",
  "NO",
  "Definitely.",
  "Ask again after the cannon.",
  "YESIDOTHINKSO",
  "Unfortunately, yes.",
  "No. Wrong moon.",
  "Probably. Top lane has seen worse.",
  "NOPERS",
  "Signs point to yes.",
  "Ornn upgraded the answer. It still says no.",
  "Maybe.",
  "Renekton says yes. Offer expires at fifteen minutes.",
  "Absolutely not.",
  "IDK",
  "Good enough to defend, bad enough to remember. BASED",
  "Outlook unclear. Tentacles.",
  "YEP",
  "Not a chance.",
  "Yes. Nobody tell bot lane.",
  "Considering",
  "The answer arrived wet. Probably yes.",
  "No. The wave is frozen.",
  "mhm",
  "A suspiciously easy yes.",
  "Ask again later.",
  "GIGANASUS",
  "Doubtful.",
  "Yes. Die for the cannon.",
  "THATSBAIT",
  "Somehow, yes.",
  "No. Ornn inspected it, grunted once, and went back to work.",
  "HAPPYIGUESS",
  "When the moon hits 0/6.",
  "Maybe. Nobody checked river.",
  "Strong no.",
  "Renekton has 50 Fury and has stopped taking questions.",
  "NoThanks",
  "Yes, but the jungler knows.",
  "Outlook: 0/3, still winnable.",
  "NAHHH",
  "NOHORNY",
  "Your wallet pinged retreat.",
  "Ask again when TP is back.",
  "PREDICTING",
  "The chair says no.",
  "Probably. Bot lane is already 0/6.",
  "HUH",
  "No. You teleported back into it.",
  "Signs point to horse.",
  "MmmHmm",
  "Darius has five stacks. That's a yes.",
  "Absolutely. Full health, full confidence, no vision.",
  "YouSureAboutThat",
  "The quietest possible maybe.",
  "SROIdWin",
  "No. The cannon died for less.",
  "Probably. Put your pants back on.",
  "Kled said yes. Skaarl left.",
  "AINTNOWAY",
  "Ask again after the dive.",
  "Yes. Rageless streamer.",
  "No. Jungle started bot.",
  "Shruge",
  "OrnnCool",
  "Yes. Smash.",
  "Probably. The minimap is decorative.",
  "BALD",
  "Illaoi pulled the spirit out of the answer. It said maybe.",
  "Never.",
  "One more wave. Then maybe.",
  "WICKEDBUSINESS",
  "No. Counterpicked.",
  "Absolutely.",
  "Singed left a yes behind him. Do not chase it.",
  "PauseChamp",
  "Outlook unclear. Four people top.",
  "Fine. Yes.",
  "Teemo says yes. Suspicious.",
  "Clueless",
  "No. Like Mike's hair, it doesn't exist. BALD",
  "Technically, maybe.",
  "Ask again when the geese clear top river.",
  "NODDERS",
  "Yes. The matchup chart can cope.",
  "A historic no.",
  "Mundo says yes. He goes where he pleases.",
  "BOOBA",
  "No. Walk back to lane.",
  "LETHIMCROC",
  "Probably. Classic SRO.",
  "The answer is under tower. Ask later.",
  "NOWAYING",
  "Yes. Take the plate and leave.",
  "Sion ulted past the answer. Probably no.",
  "Outlook unclear.",
  "Absolutely. WICKED",
  "No. That's how they get first blood.",
  "Garen says yes. He is spinning.",
  "No. Put the piss jug down.",
  "Probably. Lock in before sense arrives.",
  "No. Ranged top.",
  "British",
  "Yes. Winning lane remains unrelated.",
  "Ask again at 600 stacks.",
  "ICANT",
  "Weakside says maybe.",
  "Yes. Somebody moved Tuesday.",
  "AbsoluteDogshit",
  "No. The geese are back.",
  "Absolutely. Boobies.",
  "Darius already started walking over. Probably yes.",
  "Plotge",
  "Yes. Your team will make it difficult.",
  "No shot.",
  "Outlook unclear. The croc is scaling backward.",
  "Probably. Gooning remains undefeated.",
  "Probably. Nobody ping anything.",
  "Fiora parried the question. Ask again.",
  "TOPLANE",
  "Yes. The rest of the map is not invited.",
  "No. Go next.",
  "LETHIMCOOK",
  "The answer got counterpicked. Maybe.",
  "Signs point top. Nobody follows.",
  "No. GP put a barrel under it.",
  "Okayge",
  "Yes. Easy dubsky.",
  "Not today.",
  "Weakside. Outlook poor.",
  "Aatrox says no. Loudly.",
  "Waiting",
  "Probably. The cannon is worth more.",
  "No. That's bait.",
  "SNIFFA",
  "Yes. No counterplay. Beautiful.",
  "Ask again after top gets one gank.",
  "No. Shaco said yes.",
  "Maybe. Post-nut clarity pending.",
  "Maybe. Recall on the cannon.",
  "Absolutely. The scoreboard can catch up later.",
  "Weak maybe. Strong pull-out game.",
  "monkaSTEER",
  "No. The answer is two levels down.",
  "Yes. Lock in.",
  "Signs point to a very bad yes.",
  "No. Vayne top.",
  "Probably. Full mute angle.",
  "IHaveAnAnswer",
  "Yes. The 0/7 powerspike is online.",
  "No. Too many tentacles.",
  "WeDoALittleTrolling",
  "Ask again when the wave comes back.",
  "The answer is yes. The LP is not included.",
  "No. Sion is ulting.",
  "Maybe. Let him cook.",
  "Absolutely not. Ranged top detected.",
  "Probably. SROIdWin",
  "No. The map made other arrangements.",
  "Signs point to yes. Chat points elsewhere.",
  "For some reason, yes.",
  "Not even a little.",
  "Maybe, leaning yes.",
  "Maybe, leaning no.",
  "Ask again in five.",
  "Outlook: cooked.",
  "Yes. For content.",
  "No. Even for content.",
  "Probably. Sample size: one.",
  "Yes. Zero follow-up questions.",
  "No. Next question.",
  "Outlook unclear. Chat is typing.",
  "The answer is yes. Chat has made it worse.",
  "No. This got weird fast.",
  "Yes. This is the classic experience.",
  "No. That's not the classic experience.",
  "Ask again at 99 LP.",
  "The answer is yes, and frankly that's hilarious.",
  "No, which is probably funnier.",
  "Probably. Mike said, “we take those.”",
]);
