export const RESPONSES = Object.freeze([
  "Yes.",
  "No.",
  "Maybe.",
  "Absolutely.",
  "Not a chance.",
  "Probably.",
  "Yeah. Bad news.",
  "Nope. Unlucky.",
  "Maybe. Don't get excited.",
  "Yeah. Unfortunately.",
  "Ask again later.",
  "Ask again when chat calms down.",
  "Yeah somehow. HUH",
  "Nope somehow. ICANT",
  "Yes. Don't make it weird.",
  "Yes. This is already funny.",
  "No. That's even better.",
  "Maybe. Probably yes.",
  "Maybe. Probably no.",
  "Yes. Bot lane is not involved.",
  "No. Chat ruined it.",
  "Probably. Put your pants back on. HUH",
  "Absolutely not. Ranged top detected. GETOUTTAHERE",
  "Yes. For content. YEP",
  "No. Even for content. KEKLEO",
  "Yes. You asked too fast. Susge",
  "No. Weird thing to ask though. WhoAsked",
  "Absolutely. Nobody needed this confirmed. YOUWHAT",
  "No shot. Even the ball has standards.",
  "Yes, and MTF somehow caused it. British",
  "Maybe. Check under the desk. lookUp",
  "Yes. You are not beating the allegations. GOTEM",
  "No. British misinformation. Wrong",
  "Yes. Nobody ask why it knew that. sus",
  "You asked that like you already knew.",
  "Yes, but this feels self-incriminating. CAUGHT",
  "The ball knows what tab you closed. Pog",
  "Ask Misanthrope. He knows too much. Aware",
  "MTF has been selected as the cause. British",
  "Davey is typing. This could get worse. Chatting",
  "Onubin went quiet. HUH",
  "No, but somebody is getting blamed anyway. ModAbuse",
  "Yes. That was way too specific. NOWAYING",
  "No. Everybody saw that. watching",
  "Probably. You typed that way too confidently. KEKG",
  "Absolutely. You made it weird immediately. omgBruh",
  "No. Go shower. CLEAN",
  "Maybe. Ask again with both hands visible. PepeHands",
  "Yes, but do not make MTF explain it. muted",
  "No. The ball knows what you are. Staring",
  "Probably. Somebody check on Davey. Looking",
  "Yes. Misanthrope definitely knows something. SusgeHammer",
  "No. Onubin has left the scene. peepoLeave",
  "Maybe. The code changed again. ICANT",
  "Yes. Michael is typing too slowly to deny it. Chatting",
  "No. The British defense has collapsed. RIPBOZO",
  "Probably. Somebody is getting blamed. YEP",
  "Yes. This is getting repeated all day. StoryTime",
  "No. Delete that message. GETOUTTAHERE",
  "Only if you say it louder. peepoYELLING",
  "Ask again after somebody showers. CLEAN",
  "First part yes. Do not ask about the rest. HUH",
  "Not yet. Keep making it worse. Goblin",
  "Yes, but somebody else has to explain it. PepegaAsk",
  "Yeah sure, make it everybody's problem. WICKEDBUSINESS",
  "Continue. This can still get dumber. NOCRINGE",
  "That depends. Who is under the desk? Pog",
  "The answer changed when MTF entered the room. British",
  "One more question and this gets clipped. Hindsight",
  "Maybe. Ask it in a more incriminating way. sus",
  "No. Rephrase it with less dignity. NOCRINGE",
  "Yes. Now accuse someone else. PepePolice",
  "Probably. Keep digging. xdd",
  "Whichever one is worse. YEP",
  "That answer is between you and TotallyNotACopBro. PepePolice",
  "Yes. Everybody is pretending not to agree. HYPERNODDERS",
  "No. Nobody backed you up. peepoLeave",
  "Yes. Still weird though. YOUWHAT",
  "No. You are not innocent either. CAUGHT",
  "Probably. This got weird fast. WOT",
  "Absolutely. The timing is suspicious. Susge",
  "Yes. Mike will call it calculated. NODDERS",
  "No. Mike already used the confidence cooldown. despair",
  "Probably. Classic gaming. classic",
  "Yes. Bald advantage. BALD",
  "No. The cannon has priority.",
  "Mike can win this, which is the concerning part. AINTNOWAY",
  "Yes. The throw is still available. COPIUM",
  "No. Ranged top has ruined another perfectly good day. RIOT",
  "Probably. Chat is already blaming jungle. Complaining",
  "Mike says winnable. The screen says otherwise. COPIUM",
  "Yes. The minimap remains decorative. Clueless",
  "No. The wave is frozen.",
  "Probably. Full confidence, no vision. NODDERS",
  "Yes. Take the plate and leave. NOW",
  "No. That's how they get first blood. YOUDIED",
  "Maybe. Weakside remains a future problem. Saddies",
  "Yes. The matchup chart can cope. BASED",
  "No. Go next spiritually. Deadge",
  "Probably. The cannon is worth more. Peanut",
  "Yes. One clean fight and everybody lies about believing. BELIEVERS",
  "No. The death bush has enough customers. monkaHide",
  "Maybe. The powerspike is moving backward. omgBruh",
  "Yes. Full confidence, zero proof. GIGACHAD",
  "No. Absolutely dogshit idea. AbsoluteDogshit",
  "Probably. It goes wherever it pleases. NODDERS",
  "Yes. He grunted. That's enough. Hmm",
  "No. That got blocked somehow. NO",
  "Maybe. Late-game consequences are approaching. monkaSTEER",
  "Yes. The reset is now everybody else's problem. LETSGO",
  "No. The answer missed the exit and kept going. ICANT",
  "Probably. There are way too many tentacles involved. WOT",
  "Yes. Spin first, think never. spinning",
  "No. Somebody suspicious was involved. sus",
  "Maybe. The ride left without you. peepoBye",
  "Yes. Top lane issued a completely unbiased ruling. TOPLANE",
  "No. Jungle started bot. Case closed. PepePolice",
  "Probably. Somebody ping nothing and act natural. Clueless",
  "Yes. The health bar is now a suggestion. AINTNOWAY",
  "No. The matchup was declared illegal. RIOT",
  "Maybe. Scaling is a future-person problem. HOPIUM",
  "Yes. Extremely balanced execution. BASED",
  "No. The ult is traveling into another ZIP code. ICANT",
  "Probably. The lane has too many limbs. WOT",
  "Yes. Forward is the only available direction. peepoRun",
  "No. Somebody invisible ruined it. monkaHide",
  "Maybe. Whatever he was riding said fuck this. peepoLeave",
  "Yes. The answer came directly from top lane. TOPLANE",
  "YEP",
  "NOPERS",
  "AINTNOWAY",
  "HUH",
  "BOOBA",
  "THATSBAIT",
  "NODDERS",
  "Yes. Both hands on the keyboard. modCheck",
  "No. Wash your ass. CLEAN",
  "Probably. Freak. KEKLEO",
  "No. Keep that shit to yourself. muted",
  "Maybe. Pants status unclear. Looking",
  "Yes. The ball knows what you are. Staring",
  "No. The ball has seen enough. NOCRINGE",
  "Probably. Somebody is lying. Susge",
  "Yes. Do not clip that. NOTED",
  "No. Clip that. Cinema",
  "Maybe. Put it away. NOHORNY",
  "Absolutely not. British.",
  "Yes. He is lying. CAUGHT",
  "No. You are cooked. ThisIsFine",
  "Probably. That dude is weird. WeirdDude",
  "Ask again when Mike stops inting. COPIUM",
  "Yes. Freak behavior. Goblin",
  "No. Bald. BALD",
  "Probably. MTF did it. British",
  "Yes. Both. YESIDOTHINKSO",
  "No. Go outside. peepoLeave",
  "Maybe. Smell check failed. SNIFFA",
  "Yes. This is why Twitch warned you. CAUGHT",
  "No. Keep that in drafts. muted",
  "Probably. Do not phrase it like that again. NOCRINGE",
  "Yes. MTF made it British somehow. British",
  "No. Misanthrope already claimed the degeneracy. Goblin",
  "Maybe. Davey is still typing. Chatting",
  "Yes. Onubin will deny everything. Hmm",
  "Probably. The room smells weird now. SNIFFA",
  "Yes. Terrible use of free will. WICKED",
  "No. The bit is cooked. ThisIsFine",
  "Maybe. Keep your pants nearby. NOHORNY",
  "Yes. Bad decision approved. WICKEDBUSINESS",
  "No. Even the ball said stop. NO",
  "Probably. Everybody is pretending this is normal. NODDERS",
  "Yes. Normal guy question. HUH",
  "Maybe. Ask again after post-nut clarity. Pffftt",
  "No. The mods are looking. ModTime",
  "Probably. This ends badly. DIESOFCRINGE",
  "Yes. Caught in 4K. CAUGHT",
  "No. Shut up before chat believes you. muted",
  "Yes. Lead mod John West assigned it to the junior mod. ModTime",
  "No. That was John East Gamer. KEKW",
  "Yes, but Onubin needs to see your hall pass. Nerdge",
  "No. Hall monitor Onubin is watching. Binoculous",
  "Maybe. Misanthrope is conducting independent research. SNIFFA",
  "No. Do not let Misanthrope testify. PepePolice",
]);
